// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtvbwyfbukntmzjzfvcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dmJ3eWZidWtudG16anpmdmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzk0NzIsImV4cCI6MjA2MzYxNTQ3Mn0.SzPBND4FPiLUM50lj6AvU8VW-ovd_xeKhEjiYircn40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);